version: '3'

services:
    postgresql:
        image: postgres
        container_name: postgres
        ports:
            - "5432:5432"
        environment:
            - POSTGRES_DB=postgres
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - DATABASE_HOST=${DB_HOST}
        volumes:
            - ./schema.sql:/docker-entrypoint-initdb.d/schema.sql
            - ./postgres.conf:/etc/postgresql/postgresql.conf
            - ./data:/var/lib/postgresql/data
#        command: postgres -c config_file=/etc/postgresql/postgresql.conf
#        networks:
#            postgres-network:
        restart: always  # unless-stopped

#networks:
#    postgres-network:
#        driver: bridge
