version: '2'

services:
    zookeeper:
        image: 'bitnami/zookeeper:latest'
        ports:
            - '2181:2181'
        environment:
            - ZOO_ENABLE_AUTH=yes
            - ZOO_SERVER_USERS=kafka
            - ZOO_SERVER_PASSWORDS=kafka_password
    kafka:
        image: 'bitnami/kafka:latest'
        hostname: kafka.example.com
        ports:
            - '9092'
        environment:
            - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
            - KAFKA_CFG_LISTENERS=SASL_SSL://:9092
            - KAFKA_CFG_ADVERTISED_LISTENERS=SASL_SSL://:9092
            - KAFKA_ZOOKEEPER_USER=kafka
            - KAFKA_ZOOKEEPER_PASSWORD=kafka_password
            - KAFKA_CLIENT_USER=user
            - KAFKA_CLIENT_PASSWORD=password
            - KAFKA_CERTIFICATE_PASSWORD=certificatePassword123
            - KAFKA_CFG_TLS_TYPE=JKS # or PEM
        volumes:
            # Both .jks and .pem files are supported
            # - './kafka.keystore.pem:/opt/bitnami/kafka/config/certs/kafka.keystore.pem:ro'
            # - './kafka.keystore.key:/opt/bitnami/kafka/config/certs/kafka.keystore.key:ro'
            # - './kafka.truststore.pem:/opt/bitnami/kafka/config/certs/kafka.truststore.pem:ro'
            - './kafka.keystore.jks:/opt/bitnami/kafka/config/certs/kafka.keystore.jks:ro'
            - './kafka.truststore.jks:/opt/bitnami/kafka/config/certs/kafka.truststore.jks:ro'