version: '3.7'

services:
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: rabbitmq
        volumes:
            - ./.docker/rabbitmq/etc/:/usr/share/etc/rabbitmq/
            - ./.docker/rabbitmq/data/:/usr/share/var/lib/rabbitmq/
            - ./.docker/rabbitmq/logs/:/usr/share/var/log/rabbitmq/
        environment:
            RABBITMQ_ERLANG_COOKIE: ${RABBITMQ_ERLANG_COOKIE}
            RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
            RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
        ports:
            - 5672:5672
            - 15672:15672
        networks:
            internal-rabbit-network:

networks:
    internal-rabbit-network:
        name: internal-rabbit-network
        external: false
