version: '3'

services:

    zookeeper:
        image: confluentinc/cp-zookeeper:6.2.1
        hostname: zookeeper
        ports:
            - 2181:2181
        environment:
            ZOOKEEPER_CLIENT_PORT: 2181
            ZOOKEEPER_TICK_TIME: 2000

    kafka:
        image: confluentinc/cp-kafka:6.2.1
        hostname: kafka
        ports:
            - 9092:9092
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092,PLAINTEXT_HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
            KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'false'
            KAFKA_AUTO_LEADER_REBALANCE_ENABLE: 'true'
            KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
            KAFKA_LOG_RETENTION_MS: -1
            KAFKA_LOG_FLUSH_INTERVAL_MESSAGES: 1

    control-center:
        image: confluentinc/cp-enterprise-control-center:6.2.1
        hostname: control-center
        ports:
            - 9021:9021
        environment:
            CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka:9092
            CONTROL_CENTER_ZOOKEEPER_CONNECT: zookeeper:2181
            CONTROL_CENTER_CONNECT_CLUSTER: 'false'
            CONTROL_CENTER_KSQL_KSQLDB1_URL: http://ksqldb-server:8088
            CONTROL_CENTER_KSQL_KSQLDB1_ADVERTISED_URL: http://localhost:8088
        depends_on:
            - kafka
            - zookeeper

    ksqldb-server:
        image: confluentinc/ksqldb-server:0.20.0
        hostname: ksqldb-server
        ports:
            - 8088:8088
        environment:
            KSQL_LISTENERS: http://0.0.0.0:8088
            KSQL_BOOTSTRAP_SERVERS: kafka:9092
            KSQL_KSQL_SERVICE_ID: ksql-service-id
        depends_on:
            - kafka
            - zookeeper

    ksqldb-cli:
        image: confluentinc/ksqldb-cli:0.20.0
        depends_on:
            - ksqldb-server
        entrypoint: /bin/sh
        tty: true
